version: "2"
services:
   namenode:
      image: flokkr/hadoop:latest
      hostname: namenode
      command: ["hdfs","namenode"]
      ports:
         - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode:
      image: flokkr/hadoop:latest
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
   metastoredb:
     image: postgres
     environment:
       POSTGRES_PASSWORD: rootpwd
       POSTGRES_DB: metastore
       POSTGRES_USER: hive
   metastore:
     image: flokkr/hive
     command: ["hive","--service", "metastore"]
     env_file:
        - ./config
   hiveserver2:
     image: flokkr/hive
     command: ["hive","--service", "hiveserver2"]
     ports:
        - 10002:10002
     env_file:
        - ./config
   llap:
     image: flokkr/hive
     command: ["hive","--service", "llap"]
     env_file:
        - ./config
