
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: hive
    component: metastore
spec:
  ports:
  - port: 8080
    name: ui
  clusterIP: None
  selector:
    app: hive
    component: metastore
