
apiVersion: v1
kind: Service
metadata:
  name: hive-hiveserver2
  labels:
    app: hive
    component: hiveserver2
spec:
  ports:
  - port: 8080
    name: ui
  clusterIP: None
  selector:
    app: hive
    component: hiveserver2
