
apiVersion: v1
kind: Service
metadata:
  name: hive-metastoredb
  labels:
    app: hive
    component: metastoredb
spec:
  ports:
  - port: 8080
    name: ui
  clusterIP: None
  selector:
    app: hive
    component: metastoredb
